securityContext:
  fsGroup:
  runAsNonRoot: true
  runAsUser: 1000660006

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: service
              operator: In
              values:
                - mongodb
        topologyKey: kubernetes.io/hostname
